### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by samuelselasi**
Update **DBStorage** and **FileStorage**, adding two new methods. All changes should be done in the branch storage_get_count:

A method to retrieve one object:

- Prototype: def get(self, cls, id):

1. cls: class
2. id: string representing the object ID
3. Returns the object based on the class and its ID, or None if not found

- A method to count the number of objects in storage:

1. Prototype: def count(self, cls=None):
2. cls: class (optional)
3. Returns the number of objects in storage matching the given class. If no class is passed, returns the count of all objects in storage.

### CODE REVIEW

**Comment by samuelselasi** [comment]
Merge improved storage commit

**Comment by Titisunflower** [comment]
Merge pull request

**Comment by NewGit1999** [comment]
Reviewed pull request

**Review by samuelselasi — COMMENTED** [review]
Storage improved

**Review by samuelselasi — COMMENTED** [review]
Changes reviewed

**Review by NewGit1999 — COMMENTED** [review]
Reviewed pull request

**Pull request merged**
